# Generated by Django 6.0.7 on 2026-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the dish.', max_length=20, verbose_name='Title')),
                ('description', models.CharField(help_text='Description of the dish.', max_length=200, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price in cents.', max_digits=5, verbose_name='Price')),
            ],
        ),
    ]
