# Generated by Django 6.0.7 on 2026-07-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price in cents.', verbose_name='Price'),
        ),
    ]
