# Generated by Django 6.0.7 on 2026-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(help_text='Image of the dish.', max_length=200, verbose_name='Image'),
        ),
    ]
