# Generated by Django 6.0.7 on 2026-07-14 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, help_text='Image of the dish.', max_length=200, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(help_text='Description of the dish.', max_length=200, verbose_name='Description'),
        ),
    ]
