# Generated by Django 6.0.7 on 2026-07-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dish_image_alter_dish_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's First Name.", max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Customer's Last Name.", max_length=50, verbose_name='Last Name')),
                ('address', models.CharField(help_text="Customer's Address.", max_length=100, verbose_name='Address')),
                ('city', models.CharField(help_text="Customer's City.", max_length=50, verbose_name='City')),
                ('phone_number', models.CharField(help_text="Customer's Phone Number.", max_length=50, verbose_name='Phone Number')),
                ('message', models.TextField(blank=True, max_length=100, null=True, verbose_name='Bio')),
                ('price', models.PositiveIntegerField(default=0, help_text='Price Of The Order In Cents (Without The Tip).', verbose_name='Price')),
                ('total_price', models.PositiveIntegerField(default=0, help_text='Total Price Of The Order In Cents (With The Tip).', verbose_name='Total Price')),
                ('status', models.CharField(choices=[('PENDING', 'Čaká na platbu'), ('PAID', 'Zaplatená'), ('PREPARING', 'Pripravuje sa'), ('DELIVERING', 'Na ceste'), ('COMPLETED', 'Doručená'), ('CANCELLED', 'Zrušená')], default='PENDING', help_text="Order's status.", max_length=20, verbose_name='Order Status')),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Time of the order submission.', verbose_name='Creation Time')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of items.', verbose_name='Quantity')),
                ('price_at_purchase', models.PositiveIntegerField(default=0, help_text='Price per item in cents at the time the order was created.', verbose_name='Price At Purchase')),
                ('dish', models.ForeignKey(blank=True, help_text='The dish to which the item belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dish', verbose_name='Dish')),
                ('order', models.ForeignKey(help_text='The order to which the item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order', verbose_name='Order')),
            ],
        ),
    ]
