# Generated by Django 6.0.7 on 2026-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_tip',
            field=models.BooleanField(default=False, help_text='Stores the information if the item is tip.', verbose_name='Is Tip'),
        ),
    ]
