# Generated by Django 6.0.7 on 2026-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderitem_is_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_intent_id',
            field=models.CharField(help_text='Transaction ID in the Stripe service.', max_length=255, null=True, unique=True, verbose_name='Stripe ID'),
        ),
    ]
