# Generated by Django 6.0.7 on 2026-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_stripe_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_on_delivery',
            field=models.BooleanField(default=False, help_text='Stores information on whether the order will be paid for via cash on delivery.', verbose_name='Cash On Delivery'),
        ),
    ]
