# Generated by Django 6.0.7 on 2026-07-16 12:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_cash_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(default=app.models.generate_tracking_code, editable=False, help_text="Order's First Name.", max_length=6, unique=True, verbose_name='Tracking Code'),
        ),
    ]
