# Generated by Django 6.0.7 on 2026-07-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, help_text="Order's First Name.", max_length=6, unique=True, verbose_name='Tracking Code'),
        ),
    ]
