# Generated by Django 6.0.7 on 2026-07-16 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1, help_text='Rating from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Time of the rating submission.', verbose_name='Creation Time')),
                ('dish', models.ForeignKey(help_text='The dish to which the rating belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.dish', verbose_name='Dish')),
                ('order', models.ForeignKey(help_text='The order to which the rating belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.order', verbose_name='Order')),
            ],
            options={
                'unique_together': {('dish', 'order')},
            },
        ),
    ]
