# Generated by Django 6.0.7 on 2026-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name.", max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Customer's last name.", max_length=50, verbose_name='Last Name')),
                ('email_address', models.CharField(help_text="Customer's e-mail address.", max_length=50, verbose_name='E-mail Address')),
                ('message', models.TextField(blank=True, help_text='Message content.', max_length=250, null=True, verbose_name='Message')),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Time of the message submission.', verbose_name='Creation Time')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text="Customer's address.", max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(help_text="Customer's city.", max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text="Customer's first name.", max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(help_text="Customer's last name.", max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, help_text='Additional message or note.', max_length=100, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text="Customer's phone number.", max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price of the order in cents (without the tip).', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, help_text='Total price of the order in cents (with the tip).', verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, help_text="Order's tracking code.", max_length=6, unique=True, verbose_name='Tracking Code'),
        ),
    ]
