# Generated by Django 6.0.7 on 2026-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contactmessage_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Numerical designation of the allergen.', unique=True, verbose_name='Number')),
                ('name', models.CharField(help_text='Name or title of the allergen.', max_length=100, verbose_name='Name')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='Food allergens.', related_name='dishes', to='app.allergen', verbose_name='Allergens'),
        ),
    ]
