# Generated by Django 6.0.7 on 2026-07-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_allergen_dish_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(help_text='Name or title of the allergen.', max_length=200, verbose_name='Name'),
        ),
    ]
