# Generated by Django 6.0.7 on 2026-07-17 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_allergen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Coupon's code.", max_length=50, unique=True, verbose_name='Code')),
                ('discount_percent', models.PositiveIntegerField(default=5, help_text='Discount in percent (1–100%).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percent')),
                ('is_active', models.BooleanField(default=True, help_text='Stores the information if the coupon is still available.', verbose_name='Is Active')),
                ('valid_until', models.DateTimeField(blank=True, help_text='The time until which the coupon is valid.', null=True, verbose_name='Valid Until')),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Time of the coupon activeness.', verbose_name='Creation Time')),
            ],
        ),
    ]
