# Generated by Django 6.0.7 on 2026-07-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the soup.', max_length=250, verbose_name='Title')),
                ('price', models.PositiveIntegerField(default=0, help_text='Price in cents.', verbose_name='Price')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Pondelok'), (2, 'Utorok'), (3, 'Streda'), (4, 'Štvrtok'), (5, 'Piatok'), (6, 'Sobota'), (7, 'Nedeľa')], default=1, help_text='The day to which the daily soup belongs.', max_length=1, unique=True, verbose_name='Day Of Week')),
                ('is_active', models.BooleanField(default=True, help_text='Stores the information if the soup is still available.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Denné menu - Hlavné jedlo',
                'verbose_name_plural': 'Denné menu - Hlavné jedlá',
            },
        ),
        migrations.CreateModel(
            name='DailySoup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the soup.', max_length=250, verbose_name='Title')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Pondelok'), (2, 'Utorok'), (3, 'Streda'), (4, 'Štvrtok'), (5, 'Piatok'), (6, 'Sobota'), (7, 'Nedeľa')], default=1, help_text='The day to which the daily soup belongs.', max_length=1, unique=True, verbose_name='Day Of Week')),
                ('is_active', models.BooleanField(default=True, help_text='Stores the information if the soup is still available.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Denné menu - Polievka',
                'verbose_name_plural': 'Denné menu - Polievky',
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.PositiveIntegerField(default=0, help_text='Price per item in cents at the time the order was created (with discount).', verbose_name='Price At Purchase'),
        ),
    ]
