# Generated by Django 6.0.7 on 2026-07-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_dailymeal_dailysoup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Pondelok'), (2, 'Utorok'), (3, 'Streda'), (4, 'Štvrtok'), (5, 'Piatok'), (6, 'Sobota'), (7, 'Nedeľa')], default=1, help_text='The day to which the daily soup belongs.', max_length=1, verbose_name='Day Of Week'),
        ),
    ]
