# Generated by Django 6.0.7 on 2026-07-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_dailymeal_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeal',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Number of meal.', verbose_name='Number'),
        ),
    ]
