# Generated by Django 6.0.7 on 2026-07-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_dailymeal_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymeal',
            options={'ordering': ['number'], 'verbose_name': 'Denné menu - Hlavné jedlo', 'verbose_name_plural': 'Denné menu - Hlavné jedlá'},
        ),
    ]
