# Generated by Django 6.0.7 on 2026-07-17 19:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_dailymeal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Pondelok'), (2, 'Utorok'), (3, 'Streda'), (4, 'Štvrtok'), (5, 'Piatok'), (6, 'Sobota'), (7, 'Nedeľa')], default=1, help_text='Deň v týždni.', unique=True, verbose_name='Deň v týždni')),
                ('open_time', models.TimeField(help_text='Čas otvárania.', verbose_name='Otvárame o')),
                ('close_time', models.TimeField(help_text='Čas zatvárania.', verbose_name='Zatvárame o')),
                ('is_closed_all_day', models.BooleanField(default=False, help_text='Informácia o tom, či je prevádzka zatvorená celý deň.', verbose_name='Zatvorené celý deň')),
            ],
            options={
                'verbose_name': 'Otváracia hodina',
                'verbose_name_plural': 'Otváracie hodiny',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_force_closed', models.BooleanField(default=False, help_text='Informácia o tom, či je prevádzka mimoriadne zatvorená (napr. sviatok).', verbose_name='Je mimoriadne zatvorené')),
                ('closure_reason', models.CharField(blank=True, help_text='Dôvod zatvorenia (zobrazené na stránke).', max_length=250, null=True, verbose_name='Dôvod zatvorenia')),
            ],
            options={
                'verbose_name': 'Globálne nastavenie',
                'verbose_name_plural': 'Globálne nastavenia',
            },
        ),
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(help_text='Názov alebo označenie alergénu.', max_length=200, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='number',
            field=models.PositiveIntegerField(help_text='Číselné označenie alergénu.', unique=True, verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Čas odoslania správy.', verbose_name='Čas odoslania'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email_address',
            field=models.CharField(help_text='E-mailová adresa zákazníka.', max_length=50, verbose_name='E-mailová adresa'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(help_text='Meno zákazníka.', max_length=20, verbose_name='Meno'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(help_text='Priezvisko zákazníka.', max_length=50, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, help_text='Obsah správy.', max_length=250, null=True, verbose_name='Správa'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Kód kupónu.', max_length=50, unique=True, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Čas vytvorenia kupónu.', verbose_name='Čas vytvorenia'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.PositiveIntegerField(default=5, help_text='Zľava v percentách (1–100%).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Zľava v percentách'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Informácia o tom, či vybraný kupón je stále dostupný.', verbose_name='Je aktívny'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Čas do kedy je vybraný kupón platný.', null=True, verbose_name='Platí do'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Pondelok'), (2, 'Utorok'), (3, 'Streda'), (4, 'Štvrtok'), (5, 'Piatok'), (6, 'Sobota'), (7, 'Nedeľa')], default=1, help_text='Deň, ku ktorému patrí dené jedlo.', max_length=1, verbose_name='Deň v týždni'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Informácia o tom, či vybrané jedlo je dostupné pre tento týždeň.', verbose_name='Je aktívne'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Číslo jedla (v danom poradí sa zobrazí ponuka).', verbose_name='Číslo'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Cena v centoch.', verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='title',
            field=models.CharField(help_text='Názov jedla (celý popis, gramáž, alergény).', max_length=250, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='dailysoup',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Pondelok'), (2, 'Utorok'), (3, 'Streda'), (4, 'Štvrtok'), (5, 'Piatok'), (6, 'Sobota'), (7, 'Nedeľa')], default=1, help_text='Deň, ku ktorému patrí dená polievka.', max_length=1, unique=True, verbose_name='Deň v týždni'),
        ),
        migrations.AlterField(
            model_name='dailysoup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Informácia o tom, či vybraná polievka je dostupná pre tento týždeň.', verbose_name='Je aktívna'),
        ),
        migrations.AlterField(
            model_name='dailysoup',
            name='title',
            field=models.CharField(help_text='Názov polievky (celý popis, gramáž, alergény).', max_length=250, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='Potravinové alergény.', related_name='dishes', to='app.allergen', verbose_name='Alergény'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(help_text='Popis jedla.', max_length=200, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(help_text='Obrázok jedla (názov súboru).', max_length=200, verbose_name='Obrázok'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Cena v centoch.', verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(help_text='Názov jedla.', max_length=20, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(help_text='Adresa doručenia.', max_length=100, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_on_delivery',
            field=models.BooleanField(default=False, help_text='Informácia o tom, či vybraná objednávka bude vyplatená na dobierku alebo kartou.', verbose_name='Na dobierku'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(help_text='Mesto adresy doručenia.', max_length=50, verbose_name='Mesto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Čas vytvorenia objednávky.', verbose_name='Čas vytvorenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(help_text='Meno zákazníka.', max_length=20, verbose_name='Meno'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(help_text='Priezvisko zákazníka.', max_length=50, verbose_name='Priezvisko'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, help_text='Dodatočná správa / poznámka.', max_length=100, null=True, verbose_name='Správa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text='Telefónne číslo zákazníka.', max_length=50, verbose_name='Telefónne číslo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Cena objednávky v centoch (bez prepitného).', verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Čaká na platbu'), ('PAID', 'Zaplatená'), ('PREPARING', 'Pripravuje sa'), ('DELIVERING', 'Na ceste'), ('COMPLETED', 'Doručená'), ('CANCELLED', 'Zrušená')], default='PENDING', help_text='Aktuálny stav objednávky.', max_length=20, verbose_name='Stav objednávky'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_intent_id',
            field=models.CharField(help_text='ID transakcie v službe Stripe.', max_length=255, null=True, unique=True, verbose_name='Stripe ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, help_text='Celková cena objednávky v centoch (vrátane prepitného).', verbose_name='Celková cena'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, help_text='Sledovací kód objednávky.', max_length=6, unique=True, verbose_name='Sledovací kód'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, help_text='Jedlo ktorému zodpovedá vybraná položka.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dish', verbose_name='Jedlo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_tip',
            field=models.BooleanField(default=False, help_text='Informácia o tom, či vybraná položka je prepitné (inak je produkt).', verbose_name='Je prepitné'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Objednávka ktorej patrí daná položka.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order', verbose_name='Objednávka'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.PositiveIntegerField(default=0, help_text='Cena za položku v centoch v čase vytvorenia objednávky (vrátane zľavy).', verbose_name='Cena pri objednaní'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Množstvo položiek.', verbose_name='Množstvo'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Čas pridania hodnotenia.', verbose_name='Čas pridania'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='dish',
            field=models.ForeignKey(help_text='Jedlo ktorému vybrané hodnotenie patrí.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.dish', verbose_name='Jedlo'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(help_text='Objednávka ktorej vybrané hodnotenie patrí.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.order', verbose_name='Objednávka'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(default=1, help_text='Hodnotenie od 1 do 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Hodnotenie'),
        ),
    ]
