# Generated by Django 6.0.7 on 2026-07-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_openinghour_restaurantconfig_alter_allergen_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergen',
            options={'ordering': ['number'], 'verbose_name': 'Alergén', 'verbose_name_plural': 'Alergény'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Správa', 'verbose_name_plural': 'Správy'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Kupón', 'verbose_name_plural': 'Kupóny'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Jedlo', 'verbose_name_plural': 'Jedlá'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Objednávka', 'verbose_name_plural': 'Objednávky'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Položka objednávky', 'verbose_name_plural': 'Položky objednávky'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Hodnotenie jedla', 'verbose_name_plural': 'Hodnotenie jedál'},
        ),
    ]
