# Generated by Django 6.0.7 on 2026-07-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_allergen_options_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Názov skupiny (napr. "Vyberte si prílohu" alebo "Extra prísady").', max_length=100, verbose_name='Názov')),
                ('is_multiple_choice', models.BooleanField(default=False, help_text='Ak je zakliknuté, zákazník si môže vybrať viacero položiek. Ak nie, iba jednu.', verbose_name='Viacnásobný výber')),
                ('is_required', models.BooleanField(default=True, help_text='Musí si zákazník vybrať aspoň jednu možnosť, aby mohol jedlo vložiť do košíka?', verbose_name='Povinné')),
                ('dish', models.ForeignKey(help_text='Jedlo ktorému zodpovedá vybraná skupina prídavkov.', on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='app.dish', verbose_name='Jedlo')),
            ],
            options={
                'verbose_name': 'Skupina úprav jedla',
                'verbose_name_plural': 'Skupiny úprav jedál',
            },
        ),
        migrations.CreateModel(
            name='DishModifierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Názov položky (napr. "Hranolky" alebo "Ryža").', max_length=100, verbose_name='Názov')),
                ('extra_price', models.PositiveIntegerField(default=0, help_text='Koľko centov sa pripočíta k základnej cene jedla. 0 znamená bez doplatku.', verbose_name='Príplatok (v centoch)')),
                ('group', models.ForeignKey(help_text='Skupina ktorej zodpovedá vybraný prídavok.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.dishmodifiergroup', verbose_name='Skupina úprav')),
            ],
            options={
                'verbose_name': 'Položka úpravy',
                'verbose_name_plural': 'Položky úprav',
            },
        ),
    ]
