# Generated by Django 6.0.7 on 2026-07-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_dishmodifiergroup_dishmodifieritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(help_text='Obrázok jedla (názov súboru).', upload_to='dishes/', verbose_name='Obrázok'),
        ),
    ]
