# Generated by Django 6.0.7 on 2026-07-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Názov kategórie.', max_length=50, unique=True, verbose_name='Názov')),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategórie',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Kategória do ktorej spadá dané jedlo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='app.category', verbose_name='Kategória'),
        ),
    ]
