# Generated by Django 6.0.7 on 2026-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_category_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='<i class="fa-solid fa-list"></i>', help_text='Ikonka z https://fontawesome.com/', max_length=100, verbose_name='Ikonka (Font Awesome)'),
        ),
    ]
