# Generated by Django 6.0.7 on 2026-07-22 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Názov skupiny (napr. podľa typu, kuchyne, obmedzení, alergénov atď).', max_length=50, unique=True, verbose_name='Názov')),
            ],
            options={
                'verbose_name': 'Skupina filtrov',
                'verbose_name_plural': 'Skupiny filtrov',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-list', help_text='Ikonka z https://fontawesome.com/', max_length=100, verbose_name='Ikonka (Font Awesome)'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Skupina filtrov ku ktorej patrí daná kategória.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='app.filtergroup', verbose_name='Skupina filtrov'),
        ),
    ]
